# Generated by Django 3.0.8 on 2020-08-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cases',
            new_name='Case',
        ),
    ]
