# Generated by Django 3.0.8 on 2020-08-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200818_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
