# Generated by Django 3.0.8 on 2020-08-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200818_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='deathIncrease',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='negative',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='negativeIncrease',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='positive',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='positiveIncrease',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='recovered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
